export const PRESENTATION_DATA = {
  PROFESSION:'IDENTITY.PROFESSION',
  GREETING: 'IDENTITY.GREETING',
  NAME: 'IDENTITY.NAME',
  PROFILE: 'IDENTITY.PROFILE',
  ADDRESS: 'IDENTITY.ADDRESS',
  DESCRIPTION: 'IDENTITY.DESCRIPTION',
  JOB_FOCUS: 'IDENTITY.JOB_FOCUS',
  AVAILABILITY: 'IDENTITY.AVAILABILITY',
  SHOW_PROJECTS: 'IDENTITY.SHOW_PROJECTS',
  SHOW_CONTACT: 'IDENTITY.SHOW_CONTACT',
}
